CREATE OR REPLACE TABLE `CAD_USUARIO` (
	`ID_USUARIO` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`USU_NOME` VARCHAR(200),
	`USU_STATUS` CHAR(1),
	`USU_DATACAD` DATE,
	`USU_EMAIL` VARCHAR(255),
	`USU_SENHA` VARCHAR(255),
	`REGISTRO_STATUS` CHAR(1),
	PRIMARY KEY(`ID_USUARIO`)
);

CREATE OR REPLACE TABLE `CAD_CLIENTE` (
	`ID_CLIENTE` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`CLI_CEP` VARCHAR(10),
	`CLI_NOME` VARCHAR(150),
	`CLI_CPF` VARCHAR(14),
	`CLI_STATUS` CHAR(1),
	`CLI_DATACAD` DATE,
	`CLI_ENDERECO` VARCHAR(200),
	`CLI_NUMERO` VARCHAR(20),
	`CLI_COMPLEMENTO` VARCHAR(40),
	`CLI_BAIRRO` VARCHAR(80),
	`CLI_CIDADE` VARCHAR(50),
	`CLI_UF` CHAR(2),
	`CLI_TELEFONE` VARCHAR(15),
	`CLI_TELEFONE2` VARCHAR(15),
	`REGISTRO_STATUS` CHAR(1),
	PRIMARY KEY(`ID_CLIENTE`)
);

CREATE OR REPLACE TABLE `CAD_CATEGORIA` (
	`ID_CATEGORIA` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`CAT_DESCRICAO` VARCHAR(50),
	`CAT_STATUS` CHAR(1),
	`REGISTRO_STATUS` CHAR(1),
	PRIMARY KEY(`ID_CATEGORIA`)
);

CREATE OR REPLACE TABLE `CAD_ITEM` (
	`ID_ITEM` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`ITEM_FLAG` CHAR(1),
	`ITEM_CATEGORIA` VARCHAR(50),
	`ITEM_DESCRICAO` VARCHAR(200),
	`ITEM_UNIDADE` CHAR(2),
	`ITEM_PRECOCOMPRA` DECIMAL,
	`ITEM_PRECOVENDA` DECIMAL,
	`ITEM_ESTOQUE` DECIMAL,
	`ITEM_STATUS` CHAR(1),
	`ITEM_DATACAD` DATE,
	`REGISTRO_STATUS` CHAR(1),
	PRIMARY KEY(`ID_ITEM`)
);

